# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nike\Desktop\Scripts\Python\Testing\practic_job_5\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 461)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 340, 161, 51))
        self.pushButton.setObjectName("pushButton")

        self.quest_1 = QtWidgets.QLabel(self.centralwidget)
        self.quest_1.setGeometry(QtCore.QRect(100, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quest_1.setFont(font)
        self.quest_1.setObjectName("quest_1")

        self.quest_2 = QtWidgets.QLabel(self.centralwidget)
        self.quest_2.setGeometry(QtCore.QRect(100, 140, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quest_2.setFont(font)
        self.quest_2.setObjectName("quest_2")

        self.quest_3 = QtWidgets.QLabel(self.centralwidget)
        self.quest_3.setGeometry(QtCore.QRect(100, 200, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quest_3.setFont(font)
        self.quest_3.setObjectName("quest_3")

        self.quest_4 = QtWidgets.QLabel(self.centralwidget)
        self.quest_4.setGeometry(QtCore.QRect(100, 260, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quest_4.setFont(font)
        self.quest_4.setObjectName("quest_4")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 90, 171, 31))
        self.textEdit.setObjectName("textEdit")

        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(270, 150, 171, 31))
        self.textEdit_2.setObjectName("textEdit_2")

        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(270, 210, 171, 31))
        self.textEdit_3.setObjectName("textEdit_3")

        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(270, 270, 171, 31))
        self.textEdit_4.setObjectName("textEdit_4")

        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(150, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)

        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")

        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(280, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.time.setFont(font)
        self.time.setObjectName("time")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 533, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.pushButton.setText(_translate("MainWindow", "Проверить"))
        self.quest_1.setText(_translate("MainWindow", "Вопрос 1"))
        self.quest_2.setText(_translate("MainWindow", "Вопрос 1"))
        self.quest_3.setText(_translate("MainWindow", "Вопрос 1"))
        self.quest_4.setText(_translate("MainWindow", "Вопрос 1"))
        self.label_time.setText(_translate("MainWindow", "Время"))
        self.time.setText(_translate("MainWindow", "00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
